service: lambda-express-test

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: dist
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  serverless-offline:
    babelOptions:
      presets: ["es2017"]
